name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.5.4

      - name: Install dependencies
        run:
          sudo apt-get install python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python app.py &
          sleep 5
          curl -X POST http://localhost:5000/items -H "Content-Type: application/json" -d '{"name": "Test Item"}'
          curl http://localhost:5000/items
